version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "04:00"
  open-pull-requests-limit: 10
  labels:
  - dependencies
  - dependabot
  ignore:
  - dependency-name: "@kth/http-responses"
    versions:
    - 1.0.38
    - 1.0.39
    - 1.0.40
    - 1.0.41
    - 1.0.42
    - 1.0.43
  - dependency-name: "@kth/basic-html-templates"
    versions:
    - 1.0.36
    - 1.0.37
  - dependency-name: applicationinsights
    versions:
    - 1.8.10
  - dependency-name: mocha
    versions:
    - 8.3.0
  - dependency-name: chai
    versions:
    - 4.3.0
