version: '3'

services:
  web:
    build: .
    environment:
      TO_URL: "https://example.com"
      TEMPORARY_REDIRECT: "True"
      REDIRECT_ID: "docker-compose.yml"
      
    ports:
      - 80:80